/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
 * Generated on: 12-Mar-2025 17:52:31
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 150
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,30 -> [-4 4)  (auto determined)
 *   Product         : s29,30 -> [-2.500000e-01 2.500000e-01)  (auto determined)
 *   Accumulator     : s33,30 -> [-4 4)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
const int BL = 150;
const int16_T B[150] = {
      -44,   -427,    192,    110,     99,     77,     50,     18,    -16,
      -48,    -72,    -83,    -77,    -54,    -17,     26,     66,     95,
      104,     91,     57,      6,    -50,    -99,   -129,   -132,   -106,
      -53,     16,     87,    144,    172,    164,    118,     41,    -52,
     -140,   -204,   -226,   -199,   -124,    -14,    108,    217,    285,
      295,    238,    121,    -35,   -198,   -332,   -404,   -390,   -285,
     -103,    125,    352,    526,    601,    546,    355,     50,   -319,
     -680,   -950,  -1049,   -916,   -519,    134,    994,   1975,   2966,
     3847,   4507,   4860,   4860,   4507,   3847,   2966,   1975,    994,
      134,   -519,   -916,  -1049,   -950,   -680,   -319,     50,    355,
      546,    601,    526,    352,    125,   -103,   -285,   -390,   -404,
     -332,   -198,    -35,    121,    238,    295,    285,    217,    108,
      -14,   -124,   -199,   -226,   -204,   -140,    -52,     41,    118,
      164,    172,    144,     87,     16,    -53,   -106,   -132,   -129,
      -99,    -50,      6,     57,     91,    104,     95,     66,     26,
      -17,    -54,    -77,    -83,    -72,    -48,    -16,     18,     50,
       77,     99,    110,    192,   -427,    -44
};
