/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
 * Generated on: 12-Mar-2025 18:03:29
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 100
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s28,30 -> [-1.250000e-01 1.250000e-01)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
const int BL = 100;
const int16_T B[100] = {
      381,   -242,   -187,   -151,   -124,   -103,    -83,    -61,    -37,
      -10,     21,     54,     88,    121,    151,    175,    192,    198,
      194,    176,    146,    102,     47,    -19,    -92,   -168,   -245,
     -316,   -378,   -425,   -452,   -454,   -430,   -374,   -287,   -167,
      -15,    166,    372,    598,    839,   1088,   1335,   1575,   1799,
     1998,   2167,   2299,   2390,   2436,   2436,   2390,   2299,   2167,
     1998,   1799,   1575,   1335,   1088,    839,    598,    372,    166,
      -15,   -167,   -287,   -374,   -430,   -454,   -452,   -425,   -378,
     -316,   -245,   -168,    -92,    -19,     47,    102,    146,    176,
      194,    198,    192,    175,    151,    121,     88,     54,     21,
      -10,    -37,    -61,    -83,   -103,   -124,   -151,   -187,   -242,
      381
};
