/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
 * Generated on: 12-Mar-2025 19:33:51
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 201
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
const int BL = 201;
const int16_T B[201] = {
      -16,    -16,    -16,    -16,    -16,    -16,    -17,    -17,    -17,
      -17,    -17,    -17,    -17,    -17,    -17,    -17,    -17,    -18,
      -18,    -18,    -18,    -18,    -18,    -18,    -18,    -18,    -18,
      -18,    -18,    -18,    -19,    -19,    -19,    -19,    -19,    -19,
      -19,    -19,    -19,    -19,    -19,    -19,    -19,    -19,    -19,
      -20,    -20,    -20,    -20,    -20,    -20,    -20,    -20,    -20,
      -20,    -20,    -20,    -20,    -20,    -20,    -20,    -20,    -20,
      -20,    -20,    -21,    -21,    -21,    -21,    -21,    -21,    -21,
      -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,
      -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,
      -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,
      -21,  32747,    -21,    -21,    -21,    -21,    -21,    -21,    -21,
      -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,
      -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,
      -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,    -21,
      -21,    -20,    -20,    -20,    -20,    -20,    -20,    -20,    -20,
      -20,    -20,    -20,    -20,    -20,    -20,    -20,    -20,    -20,
      -20,    -20,    -20,    -19,    -19,    -19,    -19,    -19,    -19,
      -19,    -19,    -19,    -19,    -19,    -19,    -19,    -19,    -19,
      -18,    -18,    -18,    -18,    -18,    -18,    -18,    -18,    -18,
      -18,    -18,    -18,    -18,    -17,    -17,    -17,    -17,    -17,
      -17,    -17,    -17,    -17,    -17,    -17,    -16,    -16,    -16,
      -16,    -16,    -16
};
