/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
 * Generated on: 12-Mar-2025 19:34:46
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 101
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
const int BL = 101;
const int16_T B[101] = {
      -15,    -16,    -17,    -18,    -19,    -20,    -20,    -21,    -22,
      -23,    -24,    -25,    -26,    -26,    -27,    -28,    -29,    -30,
      -30,    -31,    -32,    -32,    -33,    -34,    -34,    -35,    -35,
      -36,    -36,    -37,    -37,    -38,    -38,    -39,    -39,    -39,
      -40,    -40,    -40,    -41,    -41,    -41,    -41,    -41,    -42,
      -42,    -42,    -42,    -42,    -42,  32726,    -42,    -42,    -42,
      -42,    -42,    -42,    -41,    -41,    -41,    -41,    -41,    -40,
      -40,    -40,    -39,    -39,    -39,    -38,    -38,    -37,    -37,
      -36,    -36,    -35,    -35,    -34,    -34,    -33,    -32,    -32,
      -31,    -30,    -30,    -29,    -28,    -27,    -26,    -26,    -25,
      -24,    -23,    -22,    -21,    -20,    -20,    -19,    -18,    -17,
      -16,    -15
};
