/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
 * Generated on: 12-Mar-2025 18:39:57
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 201
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
const int BL = 201;
const int16_T B[201] = {
      -11,     -3,     -3,     -4,     -4,     -5,     -5,     -6,     -7,
       -7,     -8,     -9,    -10,    -11,    -11,    -12,    -13,    -14,
      -16,    -17,    -18,    -19,    -20,    -22,    -23,    -25,    -26,
      -28,    -29,    -31,    -33,    -35,    -37,    -38,    -40,    -42,
      -44,    -47,    -49,    -51,    -53,    -55,    -58,    -60,    -63,
      -65,    -68,    -70,    -73,    -75,    -78,    -80,    -83,    -86,
      -88,    -91,    -94,    -96,    -99,   -102,   -105,   -107,   -110,
     -113,   -115,   -118,   -120,   -123,   -126,   -128,   -131,   -133,
     -135,   -138,   -140,   -142,   -144,   -147,   -149,   -151,   -152,
     -154,   -156,   -158,   -159,   -161,   -162,   -164,   -165,   -166,
     -167,   -168,   -169,   -170,   -170,   -171,   -171,   -172,   -172,
     -172,  32596,   -172,   -172,   -172,   -171,   -171,   -170,   -170,
     -169,   -168,   -167,   -166,   -165,   -164,   -162,   -161,   -159,
     -158,   -156,   -154,   -152,   -151,   -149,   -147,   -144,   -142,
     -140,   -138,   -135,   -133,   -131,   -128,   -126,   -123,   -120,
     -118,   -115,   -113,   -110,   -107,   -105,   -102,    -99,    -96,
      -94,    -91,    -88,    -86,    -83,    -80,    -78,    -75,    -73,
      -70,    -68,    -65,    -63,    -60,    -58,    -55,    -53,    -51,
      -49,    -47,    -44,    -42,    -40,    -38,    -37,    -35,    -33,
      -31,    -29,    -28,    -26,    -25,    -23,    -22,    -20,    -19,
      -18,    -17,    -16,    -14,    -13,    -12,    -11,    -11,    -10,
       -9,     -8,     -7,     -7,     -6,     -5,     -5,     -4,     -4,
       -3,     -3,    -11
};
