/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
 * Generated on: 12-Mar-2025 18:45:19
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 151
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
const int BL = 151;
const int16_T B[151] = {
      -11,     -4,     -5,     -6,     -7,     -8,     -9,    -10,    -11,
      -13,    -14,    -16,    -18,    -20,    -22,    -24,    -26,    -28,
      -31,    -33,    -36,    -39,    -42,    -45,    -48,    -52,    -55,
      -59,    -63,    -66,    -70,    -74,    -79,    -83,    -87,    -92,
      -96,   -101,   -105,   -110,   -114,   -119,   -124,   -129,   -133,
     -138,   -143,   -148,   -152,   -157,   -161,   -166,   -170,   -175,
     -179,   -183,   -187,   -191,   -194,   -198,   -201,   -205,   -208,
     -210,   -213,   -215,   -218,   -220,   -221,   -223,   -224,   -225,
     -226,   -227,   -227,  32541,   -227,   -227,   -226,   -225,   -224,
     -223,   -221,   -220,   -218,   -215,   -213,   -210,   -208,   -205,
     -201,   -198,   -194,   -191,   -187,   -183,   -179,   -175,   -170,
     -166,   -161,   -157,   -152,   -148,   -143,   -138,   -133,   -129,
     -124,   -119,   -114,   -110,   -105,   -101,    -96,    -92,    -87,
      -83,    -79,    -74,    -70,    -66,    -63,    -59,    -55,    -52,
      -48,    -45,    -42,    -39,    -36,    -33,    -31,    -28,    -26,
      -24,    -22,    -20,    -18,    -16,    -14,    -13,    -11,    -10,
       -9,     -8,     -7,     -6,     -5,     -4,    -11
};
