/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
 * Generated on: 12-Mar-2025 18:43:35
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 100
 * Stable            : Yes
 * Linear Phase      : Yes (Type 4)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,30 -> [-4 4)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s33,30 -> [-4 4)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
const int BL = 100;
const int16_T B[100] = {
       -6,      7,      8,      7,      2,     -6,    -15,    -18,    -13,
        2,     21,     36,     37,     19,    -15,    -52,    -73,    -65,
      -22,     44,    105,    131,    100,     13,   -101,   -194,   -216,
     -140,     18,    203,    334,    336,    182,    -91,   -383,   -561,
     -517,   -220,    254,    729,    986,    845,    249,   -681,  -1645,
    -2220,  -1933,   -265,   3859,  19750, -19750,  -3859,    265,   1933,
     2220,   1645,    681,   -249,   -845,   -986,   -729,   -254,    220,
      517,    561,    383,     91,   -182,   -336,   -334,   -203,    -18,
      140,    216,    194,    101,    -13,   -100,   -131,   -105,    -44,
       22,     65,     73,     52,     15,    -19,    -37,    -36,    -21,
       -2,     13,     18,     15,      6,     -2,     -7,     -8,     -7,
        6
};
