/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
 * Generated on: 12-Mar-2025 19:08:00
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 200
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,30 -> [-4 4)  (auto determined)
 *   Product         : s29,30 -> [-2.500000e-01 2.500000e-01)  (auto determined)
 *   Accumulator     : s33,30 -> [-4 4)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
const int BL = 200;
const int16_T B[200] = {
      -99,   -135,   -150,   -141,   -108,    -60,     -7,     36,     60,
       57,     28,    -21,    -78,   -129,   -162,   -167,   -144,    -97,
      -36,     23,     65,     80,     64,     18,    -45,   -112,   -165,
     -191,   -183,   -142,    -77,     -3,     61,    100,    102,     66,
        1,    -80,   -157,   -209,   -224,   -197,   -132,    -45,     44,
      113,    143,    126,     64,    -30,   -132,   -219,   -268,   -265,
     -209,   -110,      8,    116,    188,    203,    155,     52,    -82,
     -217,   -317,   -357,   -323,   -218,    -64,    102,    241,    315,
      302,    197,     21,   -189,   -382,   -508,   -529,   -430,   -224,
       49,    327,    540,    626,    547,    298,    -83,   -523,   -921,
    -1167,  -1168,   -859,   -227,    684,   1781,   2927,   3970,   4763,
     5190,   5190,   4763,   3970,   2927,   1781,    684,   -227,   -859,
    -1168,  -1167,   -921,   -523,    -83,    298,    547,    626,    540,
      327,     49,   -224,   -430,   -529,   -508,   -382,   -189,     21,
      197,    302,    315,    241,    102,    -64,   -218,   -323,   -357,
     -317,   -217,    -82,     52,    155,    203,    188,    116,      8,
     -110,   -209,   -265,   -268,   -219,   -132,    -30,     64,    126,
      143,    113,     44,    -45,   -132,   -197,   -224,   -209,   -157,
      -80,      1,     66,    102,    100,     61,     -3,    -77,   -142,
     -183,   -191,   -165,   -112,    -45,     18,     64,     80,     65,
       23,    -36,    -97,   -144,   -167,   -162,   -129,    -78,    -21,
       28,     57,     60,     36,     -7,    -60,   -108,   -141,   -150,
     -135,    -99
};
