/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
 * Generated on: 12-Mar-2025 19:09:01
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 100
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,30 -> [-4 4)  (auto determined)
 *   Product         : s30,30 -> [-5.000000e-01 5.000000e-01)  (auto determined)
 *   Accumulator     : s33,30 -> [-4 4)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
const int BL = 100;
const int16_T B[100] = {
      130,    199,   -203,   -140,     54,   -322,   -350,      2,   -248,
     -357,    120,     42,   -183,    310,    384,     -7,    357,    545,
      -19,    110,    412,   -231,   -355,    113,   -427,   -752,    -67,
     -310,   -787,     71,    239,   -415,    422,    993,     69,    568,
     1469,    211,     24,   1241,   -246,  -1430,    270,  -1034,  -3652,
    -1004,  -1044,  -7036,  -1894,  13751,  13751,  -1894,  -7036,  -1044,
    -1004,  -3652,  -1034,    270,  -1430,   -246,   1241,     24,    211,
     1469,    568,     69,    993,    422,   -415,    239,     71,   -787,
     -310,    -67,   -752,   -427,    113,   -355,   -231,    412,    110,
      -19,    545,    357,     -7,    384,    310,   -183,     42,    120,
     -357,   -248,      2,   -350,   -322,     54,   -140,   -203,    199,
      130
};
